### ISSUE TITLE
Trying to reproduce the tutorial.ipynb in Colab

### ISSUE THREAD

**Issue by c00n-0** [MiloszGrabski/DeepChem_MolGAN#1]
**Disclaimer**
First of all I'd like to thank @MiloszGrabski for this fantastic and exciting contribution to deepchem.
Tbh I'm relatively new to deepchem, github (and coding in general), so I'm awfully sorry in advance if the following is a trivial issue.  

**Bug description**
When trying to reproduce the example from the "tutorial.ipynb" notebook in a google Colab instance (with the github repo "cloned" to the instance), everything works fine up until the model is trained

![screenshot_molgan](https://user-images.githubusercontent.com/77687932/106483511-e2f92d00-64ae-11eb-9a66-a0bed4febc2c.png)

I've tried to enable eager execution, which did however not solve the problem.

Additional info: I'm running deepchem version 2.4.0 alongside tensorflow 2.4.1

kind regards

**Comment by MiloszGrabski** [comment]
I looks like you have something wrong with input tensors, instead of two you provide four.  From shapes I see you provide input as combination of before and after one-hot encoding.

**Comment by c00n-0** [comment]
Thanks for the answer!
From what I've seen over at the deepchem issues section it might have to do with the tensorflow version.
May I ask what tensorflow version you used for the tutorial?
I assume you utilized deepchem version 2.4.0?

thanks in advance and kind regards

**Comment by MiloszGrabski** [comment]
I have used version described in DeepChem installation. If you could share your code I might be able to help you.
I doubt from the message that this is the issue as it states that it expected two inputs but received for input tensors.
Other typical issue is not wrapping inputs into [ ] brackets, when building layers i.e. layer(input_a, input_b) might give an error while layer([input_a, input_b]) will be fine. This is due to fact that call function within layers is defined like this call(self,inputs,training=False).
